import {
    Package,
    Layers,
    Eye,
    Plus,
    Tags,
    Gauge,
    ShoppingCart,
    Users,
    LineChart,
    Settings,
    AlertCircle,
    CheckCircle,
    XCircle,
    ChevronDown,
    ChevronRight,
    MoreHorizontal,
  } from 'lucide-react';
  
  export const Icons = {
    dashboard: Gauge,
    products: Package,
    categories: Tags,
    subcategories: Layers,
    orders: ShoppingCart,
    customers: Users,
    analytics: LineChart,
    settings: Settings,
    error: AlertCircle,
    success: CheckCircle,
    warning: XCircle,
    chevronDown: ChevronDown,
    chevronRight: ChevronRight,
    more: MoreHorizontal,
    // Add all the icons you need for your dashboard
    package: Package,
    layers: Layers,
    eye: Eye,
    plus: Plus,
    category: Tags,
  };